import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import ConnectWalletButton from "./../components/ConnectWalletbutton";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="/">Solana Nft Transfer</a>
        </h1>

        <p className={styles.description}>Wallet Connect</p>
        <ConnectWalletButton />

        <div className={styles.grid}>
          <a href="https://nextjs.org/learn" className={styles.card}>
            <h2>Learn &rarr;</h2>
            <p>Learn about Next.js in an interactive course with quizzes!</p>
          </a>
        </div>
      </main>
    </div>
  );
}
